language: generic
dist: xenial

env:
  global:
  - PATH="/opt/chefdk/bin:/opt/chef/bin:/opt/chef/embedded/bin:/opt/chefdk/embedded/bin:$PATH"
  matrix:
  - COOKBOOK_PATH="cookbooks"
  - COOKBOOK_PATH="community-cookbooks"

before_script:
- curl https://omnitruck.chef.io/install.sh | sudo bash -s -- -P chefdk -v 16.16.13

script: ./runtests
